### ISSUE TITLE
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

### ISSUE THREAD

**Issue by SeekPoint** [GBLin5566/toward-controlled-generation-of-text-pytorch#8]
Epoch 0 batch 0's average language loss: 8.74623718262, latent loss: 0.00267713633366
l_attr_c loss: 0.693091034889, l_attr_z loss: 0.00270487181842
Traceback (most recent call last):
  File "train.py", line 296, in <module>
    train_vae_with_attr_loss(encoder, decoder, discriminator)
  File "train.py", line 270, in train_vae_with_attr_loss
    total_vae_loss.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 156, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 98, in backward
    variables, grad_variables, retain_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/function.py", line 91, in apply
    return self._forward_cls.backward(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/blas.py", line 30, in backward
    matrix1, matrix2 = ctx.saved_variables
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

**Comment by jonzarecki** [comment]
You can just set "retain_graph=True", however it causes all the graphs to be retained (to be expected) and it really blows up the GPU memory usage
